DatabaseFirst/DatabaseFirst/Models/Actor.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseFirst.Models
{
    public partial class Actor
    {
        public Actor()
        {
            FilmActors = new HashSet<FilmActor>();
        }

        public ushort ActorId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual ICollection<FilmActor> FilmActors { get; set; }
    }
}

DatabaseFirst/DatabaseFirst/Controllers/ActorController.cs
using AutoMapper;
using Dapper;
using DatabaseFirst.DTOs;
using DatabaseFirst.Models;
using log4net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace DatabaseFirst.Controllers
{
    public class ActorController : Controller
    {
        private readonly ILogger<ActorController> _logger;
        private readonly sakilaContext _sakilaContext;
        private readonly IMapper _mapper;
        private static readonly ILog log = LogManager.GetLogger(typeof(ActorController));
        private readonly IDbConnection _dbConnection;

        public ActorController(ILogger<ActorController> logger, sakilaContext sakilaContext, IMapper mapper, IDbConnection dbConnection)
        {
            _logger = logger;
            _sakilaContext = sakilaContext;
            _mapper = mapper;
            _dbConnection = dbConnection;
        }

        public async Task<IActionResult> List()
        {
            var actors = _sakilaContext.Actors.Select(a => a).ToList<Actor>();
            //var actors = await _dbConnection.QueryAsync<Actor>("SELECT * FROM actor");
            //var actors = await _dbConnection.QueryAsync<Actor>(
            //    "GetAllRecords",
            //    new { },
            //    commandType: CommandType.StoredProcedure
            //);


            _logger.LogInformation("Get list actors");
            log.Info("Get list actors"); //log4net
            return View(actors);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Add(Actor actor)
        {
            if (ModelState.IsValid)
            {
                //_sakilaContext.Actors.Add(actor);
                //_sakilaContext.SaveChanges();
                string sql = "INSERT INTO actor (actor_id, first_name, last_name) VALUES (@actor_id, @first_name, @last_name)";
                await _dbConnection.ExecuteAsync(sql, new { actor_id = actor.ActorId, first_name = actor.FirstName, last_name = actor.LastName });
                _logger.LogInformation("Added actor");
                return RedirectToAction("List");
            }
            else
            {
                _logger.Log(LogLevel.Error, ("Actor is invalid"));
                return StatusCode(400);
            }
        }

        public async Task<IActionResult> Details(ushort id)
        {
            //var _actor = await (_sakilaContext.Actors
            //                        .Include(b => b.FilmActors)
            //                        .ThenInclude(f => f.Film)).FirstOrDefaultAsync(a => a.ActorId == id);

            var _actor = await _sakilaContext.Actors.FirstOrDefaultAsync(a => a.ActorId == id);

            if (_actor == null)
            {
                _logger.LogWarning("Actor not found");
                return NotFound();
            }

            await _sakilaContext.Entry(_actor).Collection(a => a.FilmActors).LoadAsync(); //Reference

            List<Film> films = new List<Film>();
            foreach (var filmActor in _actor.FilmActors)
            {
                films.Add(_sakilaContext.Films.FirstOrDefault(f => f.FilmId == filmActor.FilmId));
            }

            var actorViewModel = new ActorViewModel
            {
                actor = _actor,
                Films = films
            };

            _logger.LogInformation("Get details actor " + _actor.FirstName);
            return View(actorViewModel);
        }

        [HttpGet]
        public IActionResult Edit(ushort id)
        {
            var actor = _sakilaContext.Actors.Find(id);
            if (actor == null)
            {
                _logger.LogWarning("Actor not found");
                return NotFound();
            }
            var actorDTO = _mapper.Map<ActorDTO>(actor);
            return View(actorDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ActorDTO actor)
        {
            var _actor = _sakilaContext.Actors.Find(actor.ActorId);
            if (_actor == null)
            {
                _logger.LogWarning("Actor not found");
                return NotFound();
            }

            //_mapper.Map(actor, _actor);
            //_sakilaContext.SaveChanges();

            string sql = "UPDATE actor SET first_name = @first_name, last_name = @last_name WHERE actor_id = @actor_id";
            await _dbConnection.ExecuteAsync(sql, new { actor_id = actor.ActorId, first_name = actor.FirstName, last_name = actor.LastName });

            _logger.LogInformation("Eddited actor " + _actor.FirstName);
            return RedirectToAction("List");
        }

        [HttpPost]
        public IActionResult Delete(ushort id)
        {
            var _actor = _sakilaContext.Actors.Find(id);
            if (_actor == null)
            {
                _logger.LogWarning("Actor not found");
                return NotFound();
            }
            _sakilaContext.Actors.Remove(_actor);
            _sakilaContext.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

DatabaseFirst/DatabaseFirst/Views/Actor/Add.cshtml
@model DatabaseFirst.Models.Actor

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>Actor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ActorId" class="control-label"></label>
                <input asp-for="ActorId" class="form-control" />
                <span asp-validation-for="ActorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastUpdate" class="control-label"></label>
                <input asp-for="LastUpdate" class="form-control" />
                <span asp-validation-for="LastUpdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DatabaseFirst/DatabaseFirst/Views/Actor/Details.cshtml
@model DatabaseFirst.DTOs.ActorViewModel
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Actor</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.actor.ActorId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.actor.ActorId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.actor.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.actor.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.actor.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.actor.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.actor.LastUpdate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.actor.LastUpdate)
        </dd>
    </dl>
</div>

<table>
    @foreach (var item in Model.Films)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FilmId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.actor.ActorId }) |
    <a asp-action="Index">Back to List</a>
</div>

DatabaseFirst/DatabaseFirst/Views/Actor/Edit.cshtml
@model DatabaseFirst.DTOs.ActorDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Actor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ActorId" class="control-label"></label>
                <input asp-for="ActorId" class="form-control" />
                <span asp-validation-for="ActorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastUpdate" class="control-label"></label>
                <input asp-for="LastUpdate" class="form-control" />
                <span asp-validation-for="LastUpdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DatabaseFirst/DatabaseFirst/Views/Actor/List.cshtml
@model IEnumerable<DatabaseFirst.Models.Actor>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Add">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ActorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastUpdate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ActorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastUpdate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.ActorId }) |
                @Html.ActionLink("Details", "Details", new { id=item.ActorId }) |
            </td>
            <td>
                <form asp-controller="Actor" asp-action="Delete" asp-route-id="@item.ActorId" method="post">
                    <button type="submit">Delete</button>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>